prjct/pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('products.urls', namespace = "store")),
    path('users/', include('users.urls', namespace = "users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

prjct/products/urls.py
from django.urls import path, include
from . import views
from .views import basket_add, basket_remove

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.check)
    path('catalog/', views.catalog, name='catalog'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

prjct/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('register/', views.register, name = 'register'),
    path('profile/', views.profile, name = 'profile'),
]

prjct/products/models.py
from django.db import models
import sys
sys.path.append('C:/Users/ajsha/Desktop/backend/pro/users')
from users .models import User

class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    desc = models.TextField(null=True, blank=True)
    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=256)
    desc = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='prroducts_image')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name 
    def __repr__(self) -> str:
        return self.name


class Basket(models.Model) :
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    products = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return f"Корзина товаров для {self.user.username}"

prjct/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

prjct/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class' : 'form-control py-4',
        'placeholder' : 'Введите пароль'
    }))
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control py-4',
        'placeholder' : 'Введите имя'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control py-4',
        'placeholder' : 'Введите Фамилию'
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control py-4',
        'placeholder' : 'Введите имя пользователя'
    }))

    # email = forms.CharField(widget=forms.EmailField(attrs={
    #     'class' : 'form-control py-4',
    #     'placeholder' : 'Введите почту'
    # }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class' : 'form-control py-4',
        'placeholder' : 'Введите пароль'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class' : 'form-control py-4',
        'placeholder' : 'Подтвердите почту'
    }))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control py-4'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control py-4',
    }))

    image = forms.ImageField(widget=forms.FileInput (attrs={
        'class' : 'custom-file-input'
    }), required=False)

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control py-4', 'readonly': True
    }))

    # email = forms.CharField(widget=forms.TextInput(attrs={
    #     'class' : 'form-control py-4', 'readonly': True
    # }))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

prjct/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Product, ProductCategory, Basket
import sys
sys.path.append('C:/Users/ajsha/Desktop/backend/pro/users')
from users .models import User


# Create your views here.

def catalog(request):
    context = {
        'title' : 'StoreApp',
        'products' : Product.objects.all(),
        'categories' : ProductCategory.objects.all()

    }
    return render(request, 'products/catalog.html', context)

def index(request):
    context = {
        'title': 'storeApp',
        'username' : 'Aisha Ait',
        'is_promotion' : False
    }
    return render(request, 'products/index.html', context)

def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, products=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, products=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

prjct/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import User
from django.urls import reverse
from .forms import UserLoginForm, UserRegisterForm, UserProfileForm
from django.contrib import auth
from .models import Basket


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('products:catalog'))
    else:
        form = UserLoginForm()


    context = {'form': form}
    return render(request, 'users/login.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {"title": "Store - Профиль", "form" : form, "baskets" : Basket.objects.filter(user=request.user)}
    return render(request, 'users/profile.html', context)

prjct/products/templates/products/basket.html
{% if baskets %}

    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">3</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ basket.products.name }}</h5>
                        <p class="card-text">{{ basket.products.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-light">
                            <div class="row text-center">
                                <div class="col-lg-4">
                                    <input name="basketID" type="number" class="form-control"
                                           value="{{ basket.quantity }}" min="0">
                                </div>
                                <div class="col-lg-4">2 390 руб.</div>
                                <div class="col-lg-4">
                                    <a href="{% url 'products:basket_remove' basket.id %}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
    {% endfor %}

    <div class="card mb-3">
                    <div class="card-footer">
                        <p class="float-left">Итого</p>
                        <h4 class="float-right">2 390 руб.</h4>
                    </div>
                </div>
    <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Оформить заказ
            </a>
{% else %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина пуста
    </h4>
{% endif %}

prjct/products/templates/products/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>  

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/store">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/store/catalog">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="users/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="users/profile.html">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                        <li><a class="dropdown-item" href="#">Админ-панель</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href = "#" class = "list-group-item">{{ category.name }}</a>
                {% endfor %} 
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src={{ product.image }}
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }}</h5>
                            <p class="card-text">{{ product.desc }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">
                                Отправить в корзину
                            </a>                        </div>
                    </div>
                </div>
                {% endfor %}

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body> -->

</html>




<!-- {% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Title</title>
    </head>
    <div class="col-lg-9">
    <div class = "row">
        {% for i in products %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <a href="#">
                    <img style="width:40px" class="card-img-top"
                        src="{% static 'vendor/img/products/Black-Nike-Heritage-backpack.png' %}"
                        alt="">
                </a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">{{i.name}}</a>
                    </h4>
                    <h5>{{i.price}} руб.</h5>
                    <p class="card-text">{{i.description}}</p>
                </div>
                <div class="card-footer text-center">
                    <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                </div>
            </div>
        {%endfor%}
    </div>
    </div>

    </html> -->

prjct/products/templates/products/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>

    <!-- Bootstrap core CSS -->
    <link href= "{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href= "{% static 'vendor/css/index.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href= "/store">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href= "/store/catalog">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href= "users/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href= "#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href= "users/profile.html">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href= "orders/orders.html">Заказы</a></li>
                        <li><a class="dropdown-item" href= "#">Админ-панель</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href= "#">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру!
                    {% if is_promotion %}
                        Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    {% endif %}
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href= "/store/catalog">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

<!-- Bootstrap core JavaScript -->
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="/static/vendor/fontawesome/fontawesome-icons.js" crossorigin="anonymous"></script>

</body>

</html>

prjct/users/templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Регистрация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                                Адрес электронной почты
                                            </label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{%static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>